- name: Install needed packages
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install_packages_packages:
      - python-packaging

- name: Install pulldocker
  ansible.builtin.pip:
    name: pulldocker
    virtualenv_command: "{{ ansible_facts['python']['executable'] }} -m venv"
    virtualenv: "{{ pulldocker_path }}/venv"

- name: Check if pulldocker.yaml exists
  ansible.builtin.stat:
    path: "{{ pulldocker_path }}/pulldocker.yaml"
  register: pulldocker_yaml_file

- name: Configure pulldocker
  when:
    - pulldocker_yaml is defined
    - not pulldocker_yaml_file.stat.exists
  ansible.builtin.file:
    src: "{{ pulldocker_yaml }}"
    dest: "{{ pulldocker_path }}/pulldocker.yaml"
    state: link
    force: true
    follow: false
    owner: root
    group: root

- name: Copy systemd service
  ansible.builtin.template:
    src: pulldocker.service.j2
    dest: "{{ pulldocker_path }}/pulldocker.service"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Copy systemd timer
  ansible.builtin.copy:
    src: pulldocker.timer
    dest: "{{ pulldocker_path }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Link systemd service
  ansible.builtin.file:
    src: "{{ pulldocker_path }}/pulldocker.service"
    dest: "/etc/systemd/system/pulldocker.service"
    state: link

- name: Link systemd timer
  ansible.builtin.file:
    src: "{{ pulldocker_path }}/pulldocker.timer"
    dest: "/etc/systemd/system/pulldocker.timer"
    state: link

- name: Enable systemd timer
  ansible.builtin.service:
    name: pulldocker.timer
    enabled: true
    state: started
